# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('Mr.', 'Mr.'), ('MME', 'Mme')], default='M.', max_length=3, verbose_name='Civilit\xe9')),
                ('date_naiss', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('ville', models.CharField(max_length=255)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='images_profiles')),
                ('emploie', models.BooleanField(default=False, verbose_name='Disponible pour Emploie ?')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
