"""
Django settings for social_website project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e7@xppo03li_ue4gswlic_f=^bid3d9jhh^0v)tg87*r6q*&ph'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'social-auth.com',
    'https://social-auth.com:8000/',
    'localhost',
    '127.0.0.1',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'parheto10@gmail.com'
EMAIL_HOST_PASSWORD = 'mietchomel@10#'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

#SOCIAL_AUTH_STORAGE = 'social_django_mongoengine.models.DjangoStorage'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'comptes.authenticated.EmailAuthBackup',

    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.linkedin.LinkedinOAuth',
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #app tierces
    'bootstrap4',
    'bootstrap3_datetime',
    'bootstrap4_datetime',
    'bootstrap_datepicker',
    'captcha',
    'crispy_forms',
    'django_countries',
    'phonenumber_field',
    'sorl.thumbnail',
    'social_django',

    'comptes.apps.ComptesConfig',
    'images.apps.ImagesConfig',
    'django.contrib.admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = (os.path.join(BASE_DIR, 'assets', "static_root"))

MEDIA_URL = "/media/"
MEDIA_ROOT = (os.path.join(BASE_DIR, 'static', 'medias'))

CRISPY_TEMPLATE_PACK = 'bootstrap4'

from django.core.urlresolvers import reverse_lazy
LOGIN_REDIRECT_URL = reverse_lazy('comptes:dashboard')
LOGIN_URL = reverse_lazy('comptes:login')
LOGOUT_URL = reverse_lazy('comptes:logout')

#facebook
SOCIAL_AUTH_FACEBOOK_KEY = '255179721627330'
SOCIAL_AUTH_FACEBOOK_SECRET = '6ad3a40ec02cf97ee85370f04a875470'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS =  {
    'locale':'fr_FR',
    'fields': 'name, email'
}

#twitter
SOCIAL_AUTH_TWITTER_KEY = 'AP0h7AsDObPZBh7shnMU8ShCG'
SOCIAL_AUTH_TWITTER_SECRET = 'NDNT4ayfOozBBWNxvF8srSbYX2Kvl81lpzdrVWNv7Lerip9XYH'

#google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '747977493412-hmg9j91crrel2v9nv6ib6d47dbp1c6ec.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'xS1okD59DEcsjIxv1YEbW3K8'

#github
SOCIAL_AUTH_GITHUB_KEY = 'eab5e428ad89c685f876'
SOCIAL_AUTH_GITHUB_SECRET = '02aa27463d874528945fb8006f3bf34b72569617'
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

#linkedIn
SOCIAL_AUTH_LINKEDIN_KEY = '86c5dgoxlzo7bh'
SOCIAL_AUTH_LINKEDIN_SECRET = 'ToZjowes8XBTYlwN'
#SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['user:email']
#SOCIAL_AUTH_LINKEDIN_FIELD_OAUTH2_SELECTORS = ['name, email']


# SOCIAL_AUTH_AUTHENTICATION_BACKENDS = (
#     'social_core.backends.open_id.OpenIdAuth',
#     'social_core.backends.google.GoogleOpenId',
#     'social_core.backends.google.GoogleOAuth2',
#     'social_core.backends.google.GoogleOAuth',
#     'social_core.backends.twitter.TwitterOAuth',
#     'social_core.backends.yahoo.YahooOpenId',
# )


